### ISSUE TITLE
Similarity of this set to other sets

### ISSUE THREAD

**Issue by kontaxis** [monicachew/g-analysis#6]
Jaccard index is a way to measure how similar two sets are. http://en.wikipedia.org/wiki/Jaccard_index

An index of 1 means the two sets are identical and an index of 0 means they have no common elements.

count-domains.py returns 2221 entries of which 2154 are actual unique domains.

A competitive set has 1631 unique domains.

The jaccard index for these two sets is common_unique_domains/all_unique_domains = 596/3189 ~= 0.19 which makes them pretty diverse.

**Comment by monicachew** [comment]
Fixed by #11
